name: Push To Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: NPM CI
        run: npm ci

      - name: NPM BUILD
        run: npm run build

      - name: check dist file
        run: ls -R dist

      - name: Deployer sur VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASS }}
          source: "dist/*"
          target: "/var/www/html/"
          strip_components: 1
